CREATE DATABASE zoo;
USE zoo;

/********************* BEGIN ENUMERATED DATA TYPES *********************/
CREATE TABLE ENUM_DEPARTMENT (
	dept_id					INT UNSIGNED			NOT NULL,
    dept_name				VARCHAR(30)				NOT NULL,
    CONSTRAINT ENUM_DEPARTMENT_PK
		PRIMARY KEY (dept_id),
	CONSTRAINT ENUM_DEPARTMENT_CK
		UNIQUE (dept_name)
);

CREATE TABLE ENUM_DIET_TYPE (
	diet_type_id				INT UNSIGNED			NOT NULL,
    diet_type_name				VARCHAR(15)				NOT NULL,
    CONSTRAINT ENUM_DIET_TYPE_PK
		PRIMARY KEY (diet_type_id),
	CONSTRAINT ENUM_DIET_TYPE_CK
		UNIQUE (diet_type_name)
);

CREATE TABLE ENUM_ECOSYSTEM (
	ecosystem_id			INT UNSIGNED			NOT NULL,
    ecosystem_name			VARCHAR(30)				NOT NULL,
    CONSTRAINT ENUM_ECOSYSTEM_PK
		PRIMARY KEY (ecosystem_id),
	CONSTRAINT ENUM_ECOSYSTEM_CK
		UNIQUE (ecosystem_name)
);

CREATE TABLE ENUM_FACILITY_TYPE (
	facility_type_id			INT UNSIGNED		NOT NULL,
	facility_type_name			VARCHAR(15)			NOT NULL,
	CONSTRAINT ENUM_FACILITY_TYPE_PK
		PRIMARY KEY (facility_type_id),
	CONSTRAINT ENUM_FACILITY_TYPE_CK
		UNIQUE (facility_type_name)
);

CREATE TABLE ENUM_FACILITY_STATUS (
	facility_status_id			INT UNSIGNED		NOT NULL,
	facility_status_name		VARCHAR(15)			NOT NULL,
	CONSTRAINT ENUM_FACILITY_STATUS_PK
		PRIMARY KEY (facility_status_id),
	CONSTRAINT ENUM_FACILITY_STATUS_CK
		UNIQUE (facility_status_name)
);

CREATE TABLE ENUM_HEALTH_CONDITION (
	condition_id				INT UNSIGNED			NOT NULL,
    condition_name				VARCHAR(50)				NOT NULL,
    CONSTRAINT ENUM_HEALTH_CONDITION_PK
		PRIMARY KEY (condition_id),
	CONSTRAINT ENUM_HEALTH_CONDITION_CK
		UNIQUE (condition_name)
);

CREATE TABLE ENUM_JOB_POSITION (
	position_id				INT UNSIGNED			NOT NULL,
    job_title				VARCHAR(30)				NOT NULL,
    CONSTRAINT POSITION_PK
		PRIMARY KEY (position_id)
);

CREATE TABLE ENUM_MEDICATION (
	med_id					INT UNSIGNED			NOT NULL,
    med_name				VARCHAR(30)				NOT NULL,
    CONSTRAINT ENUM_MEDICATION_PK
		PRIMARY KEY (med_id),
	CONSTRAINT ENUM_MEDICATION_CK
		UNIQUE (med_name)
);

CREATE TABLE ENUM_MEMBERSHIP_TYPE (
	member_type_id			INT UNSIGNED			NOT NULL,
    member_type_name		VARCHAR(15)				NOT NULL,
    CONSTRAINT ENUM_MEMBER_TYPE_PK
		PRIMARY KEY (member_type_id),
	CONSTRAINT ENUM_MEMBER_TYPE_CK
		UNIQUE (member_type_name)
);

CREATE TABLE ENUM_MEMBERSHIP_STATUS (
	member_status_id		INT UNSIGNED			NOT NULL,
    member_status_name		VARCHAR(15)				NOT NULL,
    CONSTRAINT ENUM_MEMBERSHIP_STATUS_PK
		PRIMARY KEY (member_status_id),
	CONSTRAINT ENUM_MEMBERSHIP_STATUS_CK
		UNIQUE (member_status_name)
);

CREATE TABLE ENUM_SECTION (
	section_id				INT UNSIGNED			NOT NULL,
    section_name			VARCHAR(30)				NOT NULL,
    CONSTRAINT ENUM_SECTION_PK
		PRIMARY KEY (section_id),
	CONSTRAINT ENUM_SECTION_CK
		UNIQUE (section_name)
);

CREATE TABLE ENUM_SPECIES (
	species_id				INT UNSIGNED			NOT NULL,
    species_name			VARCHAR(45)				NOT NULL,
    CONSTRAINT ENUM_SPECIES_PK
		PRIMARY KEY (species_id),
	CONSTRAINT ENUM_SPECIES_CK
		UNIQUE (species_name)
);

CREATE TABLE ENUM_STATE (
	state_id				CHAR(2)					NOT NULL,
    state_name				VARCHAR(30)				NOT NULL,
    CONSTRAINT ENUM_STATE_PK
		PRIMARY KEY (state_id),
	CONSTRAINT ENUM_STATE_CK
		UNIQUE (state_name)
);

CREATE TABLE ENUM_UNIT_MEASURE (
	unit_id					VARCHAR(2)				NOT NULL,
    unit_name				VARCHAR(15)				NOT NULL,
    CONSTRAINT ENUM_UNIT_MEASURE_PK
		PRIMARY KEY (unit_id),
	CONSTRAINT ENUM_UNIT_MEASURE_CK
		UNIQUE (unit_name)
);

CREATE TABLE ENUM_WORK_ORDER_TYPE (
	order_type_id			INT UNSIGNED			NOT NULL,
	order_type_name			VARCHAR(30)				NOT NULL,
    facility_type			INT UNSIGNED			NOT NULL,
	CONSTRAINT ENUM_WORK_ORDER_TYPE_PK
		PRIMARY KEY (order_type_id),
	CONSTRAINT ENUM_WORK_ORDER_TYPE_CK
		UNIQUE (order_type_name),
	CONSTRAINT ORDER_FACILITY_TYPE_FK
		FOREIGN KEY (facility_type) REFERENCES ENUM_FACILITY_TYPE(facility_type_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE
);
/********************* END ENUMERATED DATA TYPES *********************/
CREATE TABLE HEALTH_PROFILE (
	profile_id				INT UNSIGNED			NOT NULL,
    sex						ENUM('M','F')			NOT NULL,
    DOB						DATE					NOT NULL,
    weight					DECIMAL(6, 3)			NOT NULL,
    weight_unit				VARCHAR(2)				NOT NULL,
    height					DECIMAL(6, 3)			NOT NULL,
    height_unit				VARCHAR(2)				NOT NULL,
    health_condition		INT UNSIGNED			NOT NULL,
    CONSTRAINT PROFILE_PK
		PRIMARY KEY (profile_id),
	CONSTRAINT PROFILE_WUNIT_FK
		FOREIGN KEY (weight_unit) REFERENCES ENUM_UNIT_MEASURE(unit_id),
	CONSTRAINT PROFILE_HUNIT_FK
		FOREIGN KEY (height_unit) REFERENCES ENUM_UNIT_MEASURE(unit_id),
	CONSTRAINT PROFILE_CONDITION_FK
		FOREIGN KEY (health_condition) REFERENCES ENUM_HEALTH_CONDITION(condition_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT WEIGHT_MIN
		CHECK (weight > 0),
	CONSTRAINT HEIGHT_MIN
		CHECK (height > 0)
);

CREATE TABLE PRESCRIPTION (
	prescription_id			INT UNSIGNED			NOT NULL,
    health_profile			INT UNSIGNED			NOT NULL,
    medication				INT UNSIGNED			NOT NULL,
    dosage_size				DECIMAL(6, 3)			NOT NULL,
    dosage_unit				VARCHAR(2)				NOT NULL,
    doses_per_week			INT UNSIGNED			NOT NULL,
    CONSTRAINT PRESCRIPTION_PK
		PRIMARY KEY (prescription_id),
    CONSTRAINT PRESCRIPTION_PROFILE_FK
		FOREIGN KEY (health_profile) REFERENCES HEALTH_PROFILE(profile_id),
    CONSTRAINT PRESCRIPTION_MEDICATION_FK
		FOREIGN KEY (medication) REFERENCES ENUM_MEDICATION(med_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
    CONSTRAINT PRESCRIPTION_UNIT_FK
		FOREIGN KEY (dosage_unit) REFERENCES ENUM_UNIT_MEASURE(unit_id),
	CONSTRAINT DOSAGE_SIZE_MIN
		CHECK (dosage_size > 0.0)
);

CREATE TABLE DIET (
	diet_id					INT UNSIGNED			NOT NULL,
    diet_type				INT UNSIGNED			NOT NULL,
    feeding_size			DECIMAL(6, 3)			NOT NULL,
    feeding_unit			VARCHAR(2)				NOT NULL,
    feedings_per_day		INT UNSIGNED			NOT NULL,
    CONSTRAINT DIET_PK
		PRIMARY KEY (diet_id),
	CONSTRAINT DIET_TYPE_FK
		FOREIGN KEY (diet_type) REFERENCES ENUM_DIET_TYPE(diet_type_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
    CONSTRAINT DIET_UNIT_FK
		FOREIGN KEY (feeding_unit) REFERENCES ENUM_UNIT_MEASURE(unit_id),
	CONSTRAINT FEEDING_SIZE_MIN
		CHECK (feeding_size > 0.0)
);

CREATE TABLE EXHIBIT (
	exhibit_id				INT UNSIGNED			NOT NULL,
    exhibit_name			VARCHAR(30)				NOT NULL,
    exhibit_size			DECIMAL(6, 3)			NOT NULL,
    exhibit_unit			VARCHAR(2)				NOT NULL,
    ecosystem				INT UNSIGNED			NOT NULL,
    section					INT UNSIGNED			NOT NULL,
    CONSTRAINT EXHIBIT_PK
		PRIMARY KEY (exhibit_id),
	CONSTRAINT EXHIBIT_UNIT_FK
		FOREIGN KEY (exhibit_unit) REFERENCES ENUM_UNIT_MEASURE(unit_id),
	CONSTRAINT EXHIBIT_ECOSYSTEM_FK
		FOREIGN KEY (ecosystem) REFERENCES ENUM_ECOSYSTEM(ecosystem_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT EXHIBIT_SECTION_FK
		FOREIGN KEY (section) REFERENCES ENUM_SECTION(section_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT EXHIBIT_SIZE_MIN
		CHECK (exhibit_size > 0.0)
);

CREATE TABLE ANIMAL (
	animal_id				INT UNSIGNED			NOT NULL,
    animal_name				VARCHAR(15)				NOT NULL,
    species					INT UNSIGNED			NOT NULL,
    health_profile			INT UNSIGNED			NOT NULL,
    diet					INT UNSIGNED			NOT NULL,
    exhibit					INT UNSIGNED			NOT NULL,
    CONSTRAINT ANIMAL_PK
		PRIMARY KEY (animal_id),
	CONSTRAINT ANIMAL_SPECIES_FK
		FOREIGN KEY (species) REFERENCES ENUM_SPECIES(species_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT ANIMAL_PROFILE_FK
		FOREIGN KEY (health_profile) REFERENCES HEALTH_PROFILE(profile_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT ANIMAL_DIET_FK
		FOREIGN KEY (diet) REFERENCES DIET(diet_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT ANIMAL_EXHIBIT_FK
		FOREIGN KEY (exhibit) REFERENCES EXHIBIT(exhibit_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE
);

CREATE TABLE CONTACT (
    phone_no				VARCHAR(10)			NOT NULL,
    email_addr				VARCHAR(30)				NOT NULL,
    addr_line				VARCHAR(30)				NOT NULL,
    city					VARCHAR(15)				NOT NULL,
    state					CHAR(2)					NOT NULL,
    zip_code				VARCHAR(9)				NOT NULL,
    CONSTRAINT CONTACT_PK
		PRIMARY KEY (phone_no),
	CONSTRAINT CONTACT_STATE_FK
		FOREIGN KEY (state) REFERENCES ENUM_STATE(state_id)
);

CREATE TABLE EMPLOYEE (
	empl_id					INT UNSIGNED			NOT NULL,
    first_name				VARCHAR(15)				NOT NULL,
    last_name				VARCHAR(15)				NOT NULL,
    contact_info			VARCHAR(10)				NOT NULL,
    job_position			INT UNSIGNED			NOT NULL,
    department				INT UNSIGNED			NOT NULL,
    CONSTRAINT EMPL_PK
		PRIMARY KEY (empl_id),
    CONSTRAINT EMPL_CONTACT_FK
		FOREIGN KEY (contact_info) REFERENCES CONTACT(phone_no)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
    CONSTRAINT EMPL_POSITION_FK
		FOREIGN KEY (job_position) REFERENCES ENUM_JOB_POSITION(position_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT EMPL_DEPT_FK
		FOREIGN KEY (department) REFERENCES ENUM_DEPARTMENT(dept_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE
);

CREATE TABLE ANIMAL_HANDLER (
	animal_id				INT UNSIGNED			NOT NULL,
    empl_id					INT UNSIGNED			NOT NULL,
    CONSTRAINT ANIMAL_ID_FK
		FOREIGN KEY (animal_id) REFERENCES ANIMAL(animal_id)
			ON DELETE CASCADE		ON UPDATE CASCADE,
	CONSTRAINT EMPL_ID_FK
		FOREIGN KEY (empl_id) REFERENCES EMPLOYEE(empl_id)
			ON DELETE CASCADE		ON UPDATE CASCADE
);

CREATE TABLE MEMBERSHIP (
	member_id				INT UNSIGNED			NOT NULL,
    member_type				INT UNSIGNED			NOT NULL,
    first_name				VARCHAR(15)				NOT NULL,
    last_name				VARCHAR(15)				NOT NULL,
    primary_contact			VARCHAR(10)				NOT NULL,
    registration_date		DATE					NOT NULL,
    member_status			INT UNSIGNED			NOT NULL,
    CONSTRAINT MEMBER_PK
		PRIMARY KEY (member_id),
    CONSTRAINT MEMBER_TYPE_FK
		FOREIGN KEY (member_type) REFERENCES ENUM_MEMBERSHIP_TYPE(member_type_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
    CONSTRAINT MEMBER_PCONTACT_FK
		FOREIGN KEY (primary_contact) REFERENCES CONTACT(phone_no)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
    CONSTRAINT MEMBER_STATUS_FK
		FOREIGN KEY (member_status) REFERENCES ENUM_MEMBERSHIP_STATUS(member_status_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT MEMBERSHIP_UNIQUE_CONTACT
		UNIQUE(primary_key)
);

CREATE TABLE FACILITY (
	facility_id				INT UNSIGNED		NOT NULL,
    facility_name			VARCHAR(30)			NOT NULL,
	facility_type			INT UNSIGNED		NOT NULL,
	facility_status			INT UNSIGNED		NOT NULL,
    section					INT UNSIGNED		NOT NULL,
	CONSTRAINT FACILITY_PK
		PRIMARY KEY (facility_id),
	CONSTRAINT FACILITY_TYPE_FK
		FOREIGN KEY (facility_type) REFERENCES ENUM_FACILITY_TYPE(facility_type_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT FACILITY_STATUS_FK
		FOREIGN KEY (facility_status) REFERENCES ENUM_FACILITY_STATUS(facility_status_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT FACILITY_SECTION_FK
		FOREIGN KEY (section) REFERENCES ENUM_SECTION(section_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE
);

CREATE TABLE WORK_ORDER (
	order_id		INT UNSIGNED		NOT NULL,
    order_type		INT UNSIGNED		NOT NULL,
    order_date		DATE				NOT NULL,
    facility		INT UNSIGNED		NOT NULL,
	ordered_by		INT UNSIGNED		NOT NULL,
    assigned_to		INT UNSIGNED		NOT NULL,
	CONSTRAINT WORK_ORDER_PK
		PRIMARY KEY (order_id),
	CONSTRAINT WORK_ORDER_TYPE_FK
		FOREIGN KEY (order_type) REFERENCES ENUM_WORK_ORDER_TYPE(order_type_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT WORK_ORDER_FACILITY_FK
		FOREIGN KEY (facility) REFERENCES FACILITY(facility_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT WORK_ORDERED_BY_FK
		FOREIGN KEY (ordered_by) REFERENCES EMPLOYEE(empl_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE,
	CONSTRAINT WORK_ASSIGNED_TO_FK
		FOREIGN KEY (assigned_to) REFERENCES EMPLOYEE(empl_id)
			ON DELETE RESTRICT		ON UPDATE CASCADE
);

CREATE TABLE USER_LOGIN (
	user_id					INT UNSIGNED			NOT NULL,
    username				VARCHAR(15)				NOT NULL,
    user_password			VARCHAR(30)				NOT NULL,
    CONSTRAINT USER_PK
		PRIMARY KEY (user_id),
	CONSTRAINT USER_ID_FK
		FOREIGN KEY (user_id) REFERENCES EMPLOYEE(empl_id)
			ON DELETE CASCADE		ON UPDATE CASCADE
);
/********************* BEGIN TRIGGERS *********************/
CREATE TRIGGER update_facility_status
BEFORE INSERT ON work_order
FOR EACH ROW
UPDATE facility AS f, enum_facility_status AS s
SET f.facility_status = s.facility_status_id
WHERE s.facility_status_name = 'out of order' AND f.facility_id = NEW.facility;

CREATE TRIGGER on_delete_work_order
BEFORE DELETE ON work_order
FOR EACH ROW
UPDATE facility AS f, enum_facility_status AS s
SET f.facility_status = s.facility_status_id
WHERE s.facility_status_name = 'working' AND f.facility_id = OLD.facility;

CREATE TRIGGER generate_user_login
AFTER INSERT ON employee
FOR EACH ROW
INSERT INTO user_login
SELECT NEW.empl_id, CONCAT(NEW.first_name, NEW.last_name), CONCAT(NEW.first_name, NEW.last_name) from user_login;
/********************* END TRIGGERS *********************/